# Generated by Django 4.0.3 on 2022-04-10 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_userprofile_cart_alter_userprofile_courses'),
        ('account', '0002_alter_mycourse_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourse',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.userprofile'),
        ),
    ]
