# Generated by Django 4.0.3 on 2022-04-10 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_mycourse_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCourse',
        ),
    ]
