# Generated by Django 4.0.3 on 2022-04-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate')], default='Beginner', max_length=12),
        ),
    ]
