# Generated by Django 4.0.3 on 2022-04-08 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_userprofile_courses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedCourses',
        ),
    ]
