# Generated by Django 4.0.3 on 2022-04-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userprofile_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.CharField(default='\\', max_length=255),
        ),
    ]
