# Generated by Django 4.0.3 on 2022-04-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('main', '0012_userprofile_cart_remove_userprofile_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cart',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, to='account.mycourse'),
        ),
    ]
