# Generated by Django 4.0.3 on 2022-04-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_difficulty'),
        ('main', '0014_alter_userprofile_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, default=None, related_name='courses', to='course.course'),
        ),
    ]
