# Generated by Django 4.0.3 on 2022-04-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_userprofile_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='courses',
        ),
    ]
