# Generated by Django 4.0.3 on 2022-04-10 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_difficulty'),
        ('cart', '0002_order_ref_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='course.course'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
